version: '3'
services:
  psql_db:
    image: postgres:latest
    container_name: psql_server_translator
    ports:
      - 5433:5432
    restart: on-failure
    environment:
      POSTGRES_DB: translator_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database-data: